version: '3.9'
services:
  app:
    container_name: pagway-api
    image: ghcr.io/ighorpi/pagway-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    environment:
      DATABASE_URL: '${DATABASE_URL}'
      NODE_ENV: production
    networks:
      - pagway-api-network

  db:
    image: postgres
    restart: always
    ports:
      - 33700:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    networks:
      - pagway-api-network

networks:
  pagway-api-network:
    driver: bridge
